ALTER TABLE users ALTER COLUMN public_id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN public_id DROP NOT NULL;
DROP INDEX IF EXISTS users_public_id_key;
ALTER TABLE users DROP COLUMN IF EXISTS public_id;
