app = 'web-purple-shape-3897'
primary_region = 'arn'

[build]
  [build.args]
    VITE_API_URL = "https://habits-bitter-bird-9050.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
